version: "3.4"
services:

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    command:
      - sh -c python -m bot
    depends_on:
      - redis
#      - scheduler

  scheduler:
    container_name: scheduler
    build:
      context: .
      dockerfile: DockerfileScheduler
    env_file:
      - .env
    environment:
      - API_REDIS_HOST=redis
    restart: always
    depends_on:
      - redis

  redis:
    container_name: redis
    build:
      context: .
      dockerfile: DockerfileRedis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - '6379:6379'
    restart: on-failure




























