"""Create new table

Revision ID: 18127f7e8572
Revises: 
Create Date: 2024-03-03 12:44:24.074333

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "18127f7e8572"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user",
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("cars", sa.Boolean(), nullable=False),
        sa.Column("truck_cars", sa.Boolean(), nullable=False),
        sa.Column("currency", sa.String(), nullable=False),
        sa.Column("price_min", sa.Integer(), nullable=False),
        sa.Column("price_max", sa.Integer(), nullable=False),
        sa.Column("tracking_date", sa.String(), nullable=False),
        sa.PrimaryKeyConstraint("tg_id"),
        sa.UniqueConstraint("tg_id"),
    )
    op.create_table(
        "av",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("brand", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=30), nullable=False),
        sa.Column("year", sa.String(length=30), nullable=False),
        sa.Column("condition", sa.String(length=30), nullable=False),
        sa.Column("engine_type", sa.String(length=30), nullable=False),
        sa.Column("engine_capacity", sa.String(length=30), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("city", sa.String(length=60), nullable=False),
        sa.Column("price_br", sa.Integer(), nullable=False),
        sa.Column("price_usd", sa.Integer(), nullable=False),
        sa.Column("date_time_ad", sa.DateTime(), nullable=False),
        sa.Column("date_time_now", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["user.tg_id"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("link"),
    )
    op.create_table(
        "kufar",
        sa.Column("link", sa.String(), nullable=False),
        sa.Column("tg_id", sa.BigInteger(), nullable=False),
        sa.Column("brand", sa.String(length=30), nullable=False),
        sa.Column("model", sa.String(length=30), nullable=False),
        sa.Column("year", sa.String(length=30), nullable=False),
        sa.Column("condition", sa.String(length=30), nullable=False),
        sa.Column("engine_type", sa.String(length=30), nullable=False),
        sa.Column("engine_capacity", sa.String(length=30), nullable=False),
        sa.Column("region", sa.String(length=60), nullable=False),
        sa.Column("city", sa.String(length=60), nullable=False),
        sa.Column("price_br", sa.String(length=30), nullable=False),
        sa.Column("price_usd", sa.String(length=30), nullable=False),
        sa.Column("date_time_ad", sa.DateTime(), nullable=False),
        sa.Column("date_time_now", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["tg_id"], ["user.tg_id"], onupdate="CASCADE"),
        sa.PrimaryKeyConstraint("link"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("kufar")
    op.drop_table("av")
    op.drop_table("user")
    # ### end Alembic commands ###
